### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by johnmous** [tadKeys/tabsat#10]
While running it on the test data, script reaches a point where no more STDERR or STDOUT is produced. This is the last line of the combined STDERR and STDOUT:

---- Crete target lists in patternmap
-Patternmap:` removing *.log, *.target, *.jsons
.../tabsat/tabsat_test_output_miseq/Patternmap
.../tabsat/tools/Patternmap/patternmap.sh: line 181: $i: ambiguous redirect
.../tabsat/tools/Patternmap/patternmap.sh: line 182: $i: ambiguous redirect

Script keeps running for hours without any new output. A top command shows a tr tool being run

**Comment by johnmous** [comment]
Problem solved after deleting output dir and restarted the script

**Comment by spabinger** [comment]
Great to hear!
