### ISSUE TITLE
Install not quite correct

### ISSUE THREAD

**Issue by jamlover** [tadKeys/tabsat#11]
Hi. I've been trying to get the pipeline installed and feel like I put all the right pieces in place, but it seems a few things may not be right still, and I'm stumped. I have attached output streams from both test_tabsat_miseq.sh and test_tabsat_mouse.sh here. In the miseq test, it seems it runs fine but the .csv files produced in the latter stages are all empty except for the header line which (I think) messes up the final stages. In the mouse example it seems to have an error at the lollipop stage. In both cases, it seems to be missing some expected output files at the end, I'm presuming due to the earlier issues.

Also, sometimes running either example it seems to throw a samtools error at the sort stage even though the target file has been generated. This doesn't always happen and seems weird to me, but I ahae observed this outcome a few times now. If the sort fails then obviously downstream processes get compromised. Fortunately, this doesn't seem to happen frequently.

Can you please look over the attached files and see if you can get any hint of what might not be right with my configuration? And if you have any insight into the samtools error that would be great too. 

Finally, if it's of any use for you to know, I'm running  in a RedHat 7 environment with 24G of RAM, but I am doing the work on an external hard drive due to lack of space on the hard drives of the machine.

Thanks,
John Martinson

[miseq.test.txt](https://github.com/tadKeys/tabsat/files/2406767/miseq.test.txt)
[mouse.test.txt](https://github.com/tadKeys/tabsat/files/2406769/mouse.test.txt)

**Comment by jamlover** [comment]
[9-28_miseq.test.txt](https://github.com/tadKeys/tabsat/files/2429295/9-28_miseq.test.txt)
Hi. I've continued to play around without success. This is what the miseq test run output looks like as of today. I think it may be slightly different than the one from the other day so I thought I'd attach it. The bottom line is still no success though.

**Comment by tadKeys** [comment]
Dear John,

thanks for your feedback on TABSAT. I took a look at your output files and it seems to be an issue with the mapping. 

Could you please send me the output of:

`/media/MyBook/progs/tabsat-master/tools/samtools/samtools-1.4/samtools   view   /media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/SRR3296596_1_NONDIR_bowtie2/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam_removed_cov_one_sorted.bam | head
`

Furthermore, could you send me the output of this command as well:

`head /media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/SRR3296596_1_NONDIR_bowtie2/SRR3296596_trimmed_1.fastq
`

Thanks,
Stephan

**Comment by tadKeys** [comment]
Hi,

thanks for the answer. Could you please rerun this command, it seems you missed the first "/":

`/media/MyBook/progs/tabsat-master/tools/samtools/samtools-1.4/samtools view -h /media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/SRR3296596_1_NONDIR_bowtie2/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam_removed_cov_one_sorted.bam | head`

Thanks,
Stephan

**Comment by jamlover** [comment]
Oops. Sorry about that. Here is the correct command and output.

 /media/MyBook/progs/tabsat-master/tools/samtools/samtools-1.4/samtools view -h /media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/SRR3296596_1_NONDIR_bowtie2/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam_removed_cov_one_sorted.bam | head
@HD     VN:1.0  SO:coordinate
@SQ     SN:1    LN:249250621
@SQ     SN:10   LN:135534747
@SQ     SN:11   LN:135006516
@SQ     SN:12   LN:133851895
@SQ     SN:13   LN:115169878
@SQ     SN:14   LN:107349540
@SQ     SN:15   LN:102531392
@SQ     SN:16   LN:90354753
@SQ     SN:17   LN:81195210

**Comment by tadKeys** [comment]
Hi,

could you please run this command (head with more output lines):

`/media/MyBook/progs/tabsat-master/tools/samtools/samtools-1.4/samtools view -h /media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/SRR3296596_1_NONDIR_bowtie2/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam_removed_cov_one_sorted.bam | head -n 250`

Thanks,
Stephan

**Comment by jamlover** [comment]
Stephan,

As requested: Output of samtools command (attached as .txt file).
[samtools.view-h.command.250.lines.txt](https://github.com/tadKeys/tabsat/files/2446621/samtools.view-h.command.250.lines.txt)

Thanks,

John

**Comment by tadKeys** [comment]
Hi John,

sofar I don't know exactly what's going wrong - could you please send me the output of

`
ls -lR /media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/
`

Thanks and best wishes,
Stephan

**Comment by jamlover** [comment]
Stephan,


ls command output is attached. Thanks and hope this provides you with a clue!


John

________________________________

**Comment by tadKeys** [comment]
Hi John,

unfortunately I don't know whats going wrong. Would it be possible for you to zip the "/media/MyBook/progs/tabsat-master/tabsat_test_output_miseq/" folder and send it to me?

Thanks,
Stephan

**Comment by jamlover** [comment]
Stephan,

Hmmm. It's about 430 MB, so I don't know exactly how I can get that to you. Actually, now that I think about it, if you have a Microsoft account I can probably share it via OneDrive. I will need an email address associated with your Microsoft account in order to do that. If you don't already have a Microsoft account, I believe it's very easy to establish one. Please advise.

Thanks,

John

**Comment by tadKeys** [comment]
Hi John,

yes, I do have a microsoft account - please use this email address:
stephan.pabinger@ait.ac.at

Thanks,
Stephan

**Comment by jamlover** [comment]
Stephan,

I sent the OneDrive link. Hopefully it works. The md5 for the file is 37245f8f2e32124c3b2bbd85263554cb.

Thanks,

John

**Comment by jamlover** [comment]
Stephan,

I sent the OneDrive link. Hopefully it works. The md5 for the file is 37245f8f2e32124c3b2bbd85263554cb.

Thanks,

John

**Comment by tadKeys** [comment]
Hi John,

thanks for sending the file - I think I know now what's going wrong. As far as I can tell it's the used reference. TABSAT was developed and tested with a reference where the names of the chromosomes start with a "chr" prefix. It seems that your reference does not use one. Could you please try and change the TABSAT setup to a reference that uses a "chr" prefix?

In the meantime, we will work on TABSAT to accept both versions.

Thanks and best wishes,
Stephan

**Comment by jamlover** [comment]
Thanks. I will try the new version when I get a chance.

In the meantime, I substituted “chr” into the genome I was using and it worked!.....except for the lollipop plots. I think the error is because some of the input fields are thought to have duplicate names. I’ll try to figure that out on my own for now. That said, when I look at the at the “Results” .csv files in the COVERAGE_NONDIR_bowtie2 directory, I noted some of the field names have spaces in them, and start with the common prefix “READS  “ (or maybe it’s “Reads “). I’m thinking maybe that is the root of the problem. Again, I’ll see if I can troubleshoot this one on my own, but I thought you might like to know about it.

Take care,
John

**Comment by tadKeys** [comment]
Hi,

do you have any update on the issue? In the meantime I tested it on my server and it's giving me a slightly different output

```
-- Create lollipop plots for every target
Rscript --vanilla /home/app/my_version/tabsat/tools/ait/lollipop.R /home/app/my_version/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2 NONDIR bowtie2 
Loading required package: methods
NULL
$pos1
NULL

$pos2
NULL

$pos3
NULL

$pos4
NULL

$pos5
NULL

$pos6
NULL

[1] "Plotting adapted"
[1] "Done with printing"

```

**"Loading required package: methods"**

Could you please send me these files from the "COVERAGE_NONDIR_bowtie2" folder
- ResultMethylList.csv
- MethylList.csv


Thanks and best wishes,
Stephan

**Comment by jamlover** [comment]
Stephan,

I haven't had much time to work on this the last week, so I have no updates. I'm definitely still hoping to get it working fully though. I've attached the requested files.

Thanks,
John
[MethylList.csv.txt](https://github.com/tadKeys/tabsat/files/2530460/MethylList.csv.txt)
[pacbio_filtered_reads_summary.txt](https://github.com/tadKeys/tabsat/files/2530461/pacbio_filtered_reads_summary.txt)

**Comment by jamlover** [comment]
Stephan,

I haven't had much time to work on this the last week, so I have no updates. I'm definitely still hoping to get it working fully though. I've attached the requested files.

Thanks,
John
[MethylList.csv.txt](https://github.com/tadKeys/tabsat/files/2530476/MethylList.csv.txt)
[ResultMethylList.csv.txt](https://github.com/tadKeys/tabsat/files/2530477/ResultMethylList.csv.txt)

**Comment by tadKeys** [comment]
Dear John,

I pushed a new version of TABSAT that includes a fix for the lollipop issue.
Please let me know if this works for you.

Best wishes,
Stephan

**Comment by jamlover** [comment]
Stephan,

It worked! So we can close this issue. 

I will mention now that my hope/plan is to import a draft genome (produced by our group) of another organism into tabsat and see if I can get it to also function error-free. Well, actually, I've already pretty much done the importing and have most of the functions working with a few errors cropping up. I'm thinking I will try debugging those on my own since I know the pipeline is working correctly on the test data. I will let you know if I end up having success in my efforts in the end.

Thanks again for your help,
John
