### ISSUE TITLE
Hard coding of "NONDIR" in patternmap.sh

### ISSUE THREAD

**Issue by jamlover** [tadKeys/tabsat#12]
Stephan,

I think I found something that should be modified in the patternmap.sh script. The following line appears in there:
SAMPLE_C="${INDIR}/COVERAGE_NONDIR_${ALIGNER}/MethylSubpopulations/Output/SampleComparison.txt

I was doing a "DIR" run so my outputs had gone to "COVERAGE_DIR_${ALIGNER}", therefore the following error message appeared at the pattern map stage (I assume due to the hard coding of "NONDIR" in the line above):

cp /media/MyBook/progs/tabsat-master/fhm_test_output_dir_all2/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/Output/SampleComparison.txt /media/MyBook/progs/tabsat-master/fhm_test_output_dir_all2/Patternmap/All_targets.txt
cp: cannot stat ‘/media/MyBook/progs/tabsat-master/fhm_test_output_dir_all2/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/Output/SampleComparison.txt’: No such file or directory

Thought you would like to know.

John

**Comment by tadKeys** [comment]
Hi John,

I pushed a new version. Please let me know if it works for you.

Thanks and best wishes,
Stephan

**Comment by ritikgarg1234** [comment]
cannot find the file test_tabsat.sh. Please help!!
