### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by retrogenomics** [tadKeys/tabsat#2]
It is not indicated in which folder the the reference genome should be saved once downloaded. In `tabsat/reference` ?

**Comment by spabinger** [comment]
Thanks for the comment - I added the specifications to the readme

Please put the reference genome file into the following folder
Human: tabsat/reference/human/hg19/hg19.fasta
(Mouse: tabsat/reference/mouse/mm10/mm10.fasta)
