### ISSUE TITLE
bugs in samtools command lines (main tabsat script)

### ISSUE THREAD

**Issue by retrogenomics** [tadKeys/tabsat#5]
In the main `tabsat` scripts, the command lines (l. 347 & 366) for `samtools sort` should be corrected:

`samtools sort "${current_sam}_removed_cov_one.bam" "${current_sam}_removed_cov_one_sorted"`

into:

`samtools sort "${current_sam}_removed_cov_one.bam" > "${current_sam}_removed_cov_one_sorted.bam"`

and,

`samtools sort "${current_sam}_removed_cov_one.bam" "${current_sam}_removed_cov_one_sorted"`

into

`samtools sort "${current_sam}_removed_cov_one.bam" > "${current_sam}_removed_cov_one_sorted.bam"`

I don't know if this might come from changes in samtools syntaxes, but currently it does not work with samtools 1.3.1 wich is installed on our server.

**Comment by spabinger** [comment]
Thank you for this suggestion. SAMtools is now shipped with TABSAT to ensure that the correct version is used.
