### ISSUE TITLE
bugs in samtools command lines (check_quality.sh script)

### ISSUE THREAD

**Issue by retrogenomics** [tadKeys/tabsat#6]
In the `check_quality.sh` script, the following lines (l. 63 & l. 66) give an error: 

`samtools sort -o ${BAM_FILE} aa | ${INTERSECTBED} -v -a - -b ${QUALITY_DIR}/target_list.bed > ${NON_INTERSECT_BAM}`

`samtools sort -o ${BAM_FILE} aa | ${INTERSECTBED} -a - -b ${QUALITY_DIR}/target_list.bed > ${INTERSECT_BAM}`

If I understood well, it should be replaced by:

`samtools sort  ${BAM_FILE} | ${INTERSECTBED} -v -a - -b ${QUALITY_DIR}/target_list.bed > ${NON_INTERSECT_BAM}`

`samtools sort  ${BAM_FILE} | ${INTERSECTBED} -a - -b ${QUALITY_DIR}/target_list.bed > ${INTERSECT_BAM}`

**Comment by spabinger** [comment]
Thanks for the hint. Fixed in the version https://github.com/tadKeys/tabsat/commit/4c8fcdcff727515b1e7024c18f4f77bd1c308096 .
