### ISSUE TITLE
bug in patternmap.sh script

### ISSUE THREAD

**Issue by retrogenomics** [tadKeys/tabsat#7]
In the `patternmap.sh`script, the variable `SAMPLE_C` contains the `COVERAGE_NONDIR_tmap`path, which does not exist if bowtie2 is used as aligner:  `SAMPLE_C="${INDIR}/COVERAGE_NONDIR_tmap/MethylSubpopulations/Output/SampleComparision.txt"`

This makes the `test_tabsat_miseq.sh`script to crash. An ALIGNER variable should be defined (see also this issue: https://github.com/tadKeys/tabsat/issues/4).

**Comment by spabinger** [comment]
Thanks for the pointer. I have included your suggestion.
