### ISSUE TITLE
error running test

### ISSUE THREAD

**Issue by retrogenomics** [tadKeys/tabsat#8]
I have the following error when running the test for miseq (in bold). It might come from the `(...)-zz_test/SRR3296596_1.fastq` which should not contain the '-' before 'zz_test'. I have tried to figure out why this character was inserted, but I couldn't find so far.

> - CMD subpopulations: /home/gcristofari/tools/tabsat/tools/MethylSubpop/subpopulations.sh -i /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations -p 0.7 -t /home/gcristofari/tools/tabsat/tools/zz_test/target_list_miseq.csv
> Starting with methylation pattern analysis
> Output will be saved in /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/Output
> Whole Target for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Intermediate Positions for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Paste intermediate Positions for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Intermediate Subpops for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Final Positions for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Paste final Positions for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Final Subpops for /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/COVERAGE_NONDIR_bowtie2/MethylSubpopulations/SRR3296596_trimmed_1.fastq_bismark_bt2_pe.sam
> Comparision of first and last methylation positions in all samples
> Finding methylation subpopulations
> Done with workflow
> **mv: cannot stat '/home/gcristofari/tools/tabsat/tools/-zz_test/SRR3296596_1.fastq /home/gcristofari/tools/tabsat/tools/zz_test/SRR3296596_2.fastq': No such file or directory**
> 
> - CMD patternmap: /home/gcristofari/tools/tabsat/tools/Patternmap/patternmap.sh -i /home/gcristofari/tools/tabsat/tabsat_test_output_miseq -s /home/gcristofari/tools/tabsat/tabsat_test_output_miseq/copied_inputs -t /home/gcristofari/tools/tabsat/tools/zz_test/target_list_miseq.csv
>

**Comment by spabinger** [comment]
I have fixed the error. The test should now run through.
